### PR TITLE
docs: Add rkt, Docker, and Kubernetes bootcfg deployment notes

### LINKED ISSUE #93: docs: Deployment via Kubernetes

### PR DESCRIPTION
**Pull request by dghubble**
* Resolves #93

### CODE REVIEW

**Comment by dghubble** [comment]
@colhom Does infra have a NodePort selection policy? I've used  32401 in the `bootcfg` example, a random-ish choice. Asking because you chose a port in https://github.com/coreos/docker-nginx-https-redirect/blob/master/contrib/k8s/https-redirect-service.yaml#L11

**Comment by colhom** [comment]
@dghubble no real rule for assigning node ports. I tend to use 31XXX for production services, and 32XXX for their staging analogues. Just a "pattern", not really a rule.

I expect that we'll be transitioning away from nodeports as we can make better use of load-balancer services anyways. Maintaining this mapping out-of-band is hideous.

**Comment by dghubble** [comment]
I'll just use the randomly selected 31488 NodePort for the generic example then. Folks who have k8s compatible load balancers can edit how they like. Thanks Colin!

**Comment by chancez** [comment]
BTW, you should be able to not specify the node port, and k8s will pick for you, alternatively, I'd actually say you should just leave it at `type: ClusterIP` as the default.

**Comment by dghubble** [comment]
Hm, maybe I've optimized for my typical use cases. I choose a fixed NodePort per service globally (rather than letting k8s decide) to support load balancing across nodes in multiple Kubernetes clusters (baby ubernetes). The Service IP is determined at the load balancer level.

What's your aim for using ClusterIP in the example?

**Comment by chancez** [comment]
Well, I guess using a clusterIP doesnt make much sense, since nodes wont be on the k8s network, thus they wouldn't be able to use the clusterIP to access it. Never mind.

**Comment by joeatwork** [comment]
+1 for fixed ports in examples

**Pull request merged**
