### PR TITLE
examples: Bump k8s and k8s-install to CoreOS 1122.0.0

### PR DESCRIPTION
**Pull request by dghubble**
cc @Titerote @mischief from IRC discussion.

Following the qemu/kvm PXE boot [tutorial](https://github.com/coreos/coreos-baremetal/blob/1f5c7a6d5a6ddb2fa1416f964d16a852289d069b/Documentation/kubernetes.md) for `k8s` on CoreOS 1122.0.0.

```
$ kubectl --kubeconfig=examples/assets/tls/kubeconfig describe nodes
Name:			node1.example.com
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=node1.example.com
Taints:			<none>
CreationTimestamp:	Sun, 21 Aug 2016 17:15:17 -0700
Phase:			
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  OutOfDisk 		False 	Sun, 21 Aug 2016 17:17:47 -0700 	Sun, 21 Aug 2016 17:15:17 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Sun, 21 Aug 2016 17:17:47 -0700 	Sun, 21 Aug 2016 17:15:17 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Sun, 21 Aug 2016 17:17:47 -0700 	Sun, 21 Aug 2016 17:15:17 -0700 	KubeletReady 			kubelet is posting ready status
Addresses:		172.15.0.21,172.15.0.21
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				1020980Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				1020980Ki
 pods:					110
System Info:
 Machine ID:			748cfc5d0ac0444e85d1cccb08411403
 System UUID:			93E58FF7-D06D-444A-BEB2-624F1121AB81
 Boot ID:			f60cca30-5eb4-47b9-84e9-c2cb8ed15502
 Kernel Version:		4.7.0-coreos
 OS Image:			CoreOS 1122.0.0 (MoreOS)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.11.2
 Kubelet Version:		v1.3.4+coreos.0
 Kube-Proxy Version:		v1.3.4+coreos.0
ExternalID:			node1.example.com
Non-terminated Pods:		(4 in total)
  Namespace			Name							CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----							------------	----------	---------------	-------------
  kube-system			kube-apiserver-node1.example.com			0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-controller-manager-node1.example.com		200m (20%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-proxy-node1.example.com				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-scheduler-node1.example.com			100m (10%)	0 (0%)		0 (0%)		0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  300m (30%)	0 (0%)		0 (0%)		0 (0%)
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  4m		4m		1	{kubelet node1.example.com}			Normal		Starting		Starting kubelet.
  4m		2m		46	{kubelet node1.example.com}			Normal		NodeHasSufficientDisk	Node node1.example.com status is now: NodeHasSufficientDisk
  4m		2m		46	{kubelet node1.example.com}			Normal		NodeHasSufficientMemory	Node node1.example.com status is now: NodeHasSufficientMemory
  2m		2m		1	{controllermanager }				Normal		RegisteredNode		Node node1.example.com event: Registered Node node1.example.com in NodeController


Name:			node2.example.com
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=node2.example.com
Taints:			<none>
CreationTimestamp:	Sun, 21 Aug 2016 17:15:16 -0700
Phase:			
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  OutOfDisk 		False 	Sun, 21 Aug 2016 17:17:47 -0700 	Sun, 21 Aug 2016 17:15:16 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Sun, 21 Aug 2016 17:17:47 -0700 	Sun, 21 Aug 2016 17:15:16 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Sun, 21 Aug 2016 17:17:47 -0700 	Sun, 21 Aug 2016 17:15:16 -0700 	KubeletReady 			kubelet is posting ready status
Addresses:		172.15.0.22,172.15.0.22
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				1020980Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				1020980Ki
 pods:					110
System Info:
 Machine ID:			748cfc5d0ac0444e85d1cccb08411403
 System UUID:			47F9FEB4-A6B0-4B55-A65F-0438CEAF65EB
 Boot ID:			81184187-f2c0-46a5-ba22-099ed43cc321
 Kernel Version:		4.7.0-coreos
 OS Image:			CoreOS 1122.0.0 (MoreOS)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.11.2
 Kubelet Version:		v1.3.4+coreos.0
 Kube-Proxy Version:		v1.3.4+coreos.0
ExternalID:			node2.example.com
Non-terminated Pods:		(2 in total)
  Namespace			Name					CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----					------------	----------	---------------	-------------
  kube-system			kube-dns-v15-q79ap			110m (11%)	110m (11%)	70Mi (7%)	220Mi (22%)
  kube-system			kube-proxy-node2.example.com		0 (0%)		0 (0%)		0 (0%)		0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  110m (11%)	110m (11%)	70Mi (7%)	220Mi (22%)
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  4m		4m		1	{kubelet node2.example.com}			Normal		Starting		Starting kubelet.
  4m		2m		25	{kubelet node2.example.com}			Normal		NodeHasSufficientDisk	Node node2.example.com status is now: NodeHasSufficientDisk
  4m		2m		25	{kubelet node2.example.com}			Normal		NodeHasSufficientMemory	Node node2.example.com status is now: NodeHasSufficientMemory
  2m		2m		1	{controllermanager }				Normal		RegisteredNode		Node node2.example.com event: Registered Node node2.example.com in NodeController


Name:			node3.example.com
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=node3.example.com
Taints:			<none>
CreationTimestamp:	Sun, 21 Aug 2016 17:15:17 -0700
Phase:			
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  OutOfDisk 		False 	Sun, 21 Aug 2016 17:17:48 -0700 	Sun, 21 Aug 2016 17:15:17 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Sun, 21 Aug 2016 17:17:48 -0700 	Sun, 21 Aug 2016 17:15:17 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Sun, 21 Aug 2016 17:17:48 -0700 	Sun, 21 Aug 2016 17:15:17 -0700 	KubeletReady 			kubelet is posting ready status
Addresses:		172.15.0.23,172.15.0.23
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				1020980Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				1020980Ki
 pods:					110
System Info:
 Machine ID:			748cfc5d0ac0444e85d1cccb08411403
 System UUID:			C973F03F-CC5D-4E8F-9281-BFB8239E7BFC
 Boot ID:			40fc9149-4171-4ec3-84c6-abe6848bb492
 Kernel Version:		4.7.0-coreos
 OS Image:			CoreOS 1122.0.0 (MoreOS)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.11.2
 Kubelet Version:		v1.3.4+coreos.0
 Kube-Proxy Version:		v1.3.4+coreos.0
ExternalID:			node3.example.com
Non-terminated Pods:		(3 in total)
  Namespace			Name						CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----						------------	----------	---------------	-------------
  kube-system			heapster-v1.1.0-3647315203-yvtx8		158m (15%)	158m (15%)	364Mi (36%)	364Mi (36%)
  kube-system			kube-proxy-node3.example.com			0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kubernetes-dashboard-v1.1.0-lloak		100m (10%)	100m (10%)	50Mi (5%)	50Mi (5%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  258m (25%)	258m (25%)	414Mi (41%)	414Mi (41%)
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  3m		3m		1	{kubelet node3.example.com}			Normal		Starting		Starting kubelet.
  3m		2m		23	{kubelet node3.example.com}			Normal		NodeHasSufficientDisk	Node node3.example.com status is now: NodeHasSufficientDisk
  3m		2m		23	{kubelet node3.example.com}			Normal		NodeHasSufficientMemory	Node node3.example.com status is now: NodeHasSufficientMemory
  2m		2m		1	{controllermanager }				Normal		RegisteredNode		Node node3.example.com event: Registered Node node3.example.com in NodeController
```

### CODE REVIEW

**Comment by Titerote** [comment]
I haven't managed to make it work. I changed the ignition profile to a vanilla etcd, but with a storage section to it so I could test dropping a file (in this case /etc/flannel/options.env). File can be found at:

https://gist.githubusercontent.com/Titerote/f508e8cd735d2463da5ae2fcaeec1215/raw/1ee62051144fff9f8ed7aa2a3c28ca6b25800317/ignition_config_vanillaetcd.yml

Same symptoms, sda1 gets a fs which I can mount and I see within there the etc/flannel/options.env with it's content, but looks like the root switch did not happen (despite what journalctl says)

**Comment by dghubble** [comment]
What's in `/dev/disk/by-label`?

**Comment by Titerote** [comment]
Thi is what I see there: 

lrwxrwxrwx. 1 root root 10 Aug 22 21:56 ROOT -> ../../sda1

**Comment by dghubble** [comment]
This might be related to a by-label race @crawford mentioned to me. Perhaps there is a coreos/bugs issue for this?

Somewhat pertinent, the examples are going to be updated to use the universal root filesystem (not custom "rootfs"). https://github.com/coreos/coreos-baremetal/pull/324

**Comment by Titerote** [comment]
I didn't find reported coreos bug on this. The thing is that the examples
work fine when I use local docker0 bridge and the provided dnsmasq, but as
soon as I try to move those plain samples to a different network I run into
this issue.

Is the race condition mentioned by @crawford that one where ignition did
not retry/wait for the network when pulling the config from remote ? I
believe there was a fix on the way for that on Alpha. I'd love to try it
out as soon as it comes out, see if that fixes the issue.

I will setup same samples using real networking, and move from there, see
if I can identify the step that breaks them, but that will take a bit of
time, since my lab needs adjustments for that.

I totally agree on the rootfs, I can see (with the systemd.debug), that
it's not being affected and works like a charm. Maybe changing the ignition
templates to write there would work ? is that your suggestion ?

Joe

**Comment by dghubble** [comment]
Changing from "rootfs" to "root" is just a simplification now that there is a default named root filesystem (ramdisk on PXE). If you're PXE booting, that's the simplest. The Kubernetes examples (when pxe:true) are unique from the other cluster examples - a RAM disk is not large enough so a root filesystem kernel arg is provided and Ignition is used to create a filesystem on that device. From README

> Some examples check the pxe variable to determine whether to create a /dev/sda1 filesystem and partition for PXEing with root=/dev/sda1 ("pxe":"true") or to write files to the existing filesystem on /dev/disk/by-label/ROOT ("pxe":"false").

My suspicion is that this is either the udev race (different from Ignition retry timeout) or simple confusion by mixing and matching different Ignition examples.

If I recall, you were the one who posted some gists with specfic info. *Mind creating a separate issue about your filesystem findings/issue and linking the info you have*? Just bc this PR is an odd place for a longer discussion on this.

**Comment by dghubble** [comment]
Let's bump the CoreOS version for all reference clusters when the next alpha is released.

**Pull request closed without merging**
