### PR TITLE
examples: Run Torus' etcd3 with rkt

### LINKED ISSUE #325: Update Torus reference example to run etcd3 with rkt

### PR DESCRIPTION
**Pull request by dghubble**
* Run Torus' etcd3 with rkt

cc @barakmich 
closes #325

### CODE REVIEW

**Comment by dghubble** [comment]
With or without this change, the Torus cluster no longer seems to function properly.

Attempting to create a filesystem, writes are failing.

```
sudo ./torusblk --etcd=172.15.0.21:2379 nbd hello /dev/nbd0
sudo mkfs.ext4 /dev/nbd0
```

Meanwhile, 

```
sudo ./torusblk --etcd=172.15.0.21:2379 nbd hello /dev/nbd0
Connected to /dev/nbd0
2016-08-24 23:34:22.551817 E | distributor: error resetConn: grpc: the client connection is closing
2016-08-24 23:34:22.551920 N | distributor: error WriteAll to peer d61b6eec-6a8d-11e6-aeab-525400c36177: rpc error: code = 2 desc = grpc: the client connection is closing
2016-08-24 23:34:23.566874 E | distributor: error resetConn: grpc: the client connection is closing
2016-08-24 23:34:23.566955 N | distributor: error WriteAll to peer cd7bf076-6a8d-11e6-a624-525400a19cae: rpc error: code = 2 desc = grpc: the client connection is closing
2016-08-24 23:34:24.579501 E | distributor: error resetConn: grpc: the client connection is closing
2016-08-24 23:34:24.579581 N | distributor: error WriteAll to peer d6c597f9-6a8d-11e6-9c00-525400b22f86: rpc error: code = 2 desc = grpc: the client connection is closing
2016-08-24 23:34:24.579623 N | distributor: error WriteAll to all peers
2016-08-24 23:34:25.591056 E | distributor: error resetConn: grpc: the client connection is closing
2016-08-24 23:34:25.591207 N | distributor: error WriteAll to peer d61b6eec-6a8d-11e6-aeab-525400c36177: rpc error: code = 2 desc = grpc: the client connection is closing
2016-08-24 23:34:26.600115 E | distributor: error resetConn: grpc: the client connection is closing
2016-08-24 23:34:26.600194 N | distributor: error WriteAll to peer cd7bf076-6a8d-11e6-a624-525400a19cae: rpc error: code = 2 desc = grpc: the client connection is closing
2016-08-24 23:34:27.611626 E | distributor: error resetConn: grpc: the client connection is closing
2016-08-24 23:34:27.611725 N | distributor: error WriteAll to peer d6c597f9-6a8d-11e6-9c00-525400b22f86: rpc error: code = 2 desc = grpc: the client connection is closing
2016-08-24 23:34:27.611760 N | distributor: error WriteAll to all peers
2016-08-24 23:34:28.679029 E | distributor: error resetConn: grpc: the client connection is closing
2016-08-24 23:34:28.679184 N | distributor: error WriteAll to peer d61b6eec-6a8d-11e6-aeab-525400c36177: rpc error: code = 2 desc = grpc: the client connection is closing
2016-08-24 23:34:29.687690 E | distributor: error resetConn: grpc: the client connection is closing
2016-08-24 23:34:29.687782 N | distributor: error WriteAll to peer d6c597f9-6a8d-11e6-9c00-525400b22f86: rpc error: code = 2 desc = grpc: the client connection is closing
2016-08-24 23:34:30.696410 E | distributor: error resetConn: grpc: the client connection is closing
2016-08-24 23:34:30.696487 N | distributor: error WriteAll to peer cd7bf076-6a8d-11e6-a624-525400a19cae: rpc error: code = 2 desc = grpc: the client connection is closing
2016-08-24 23:34:30.696560 N | distributor: error WriteAll to all peers
...
```

```
./torusctl --etcd 172.15.0.21:2379 list-peers
+--------------------------------+--------------------------------------+---------+------+--------+--------------+--------------+
|            ADDRESS             |                 UUID                 |  SIZE   | USED | MEMBER |   UPDATED    | REB/REP DATA |
+--------------------------------+--------------------------------------+---------+------+--------+--------------+--------------+
| http://node1.example.com:40000 | cd7bf076-6a8d-11e6-a624-525400a19cae | 1.0 GiB | 0 B  | OK     | now          | 0 B/sec      |
| http://node3.example.com:40000 | d61b6eec-6a8d-11e6-aeab-525400c36177 | 1.0 GiB | 0 B  | OK     | 1 second ago | 0 B/sec      |
| http://node2.example.com:40000 | d6c597f9-6a8d-11e6-9c00-525400b22f86 | 1.0 GiB | 0 B  | OK     | now          | 0 B/sec      |
+--------------------------------+--------------------------------------+---------+------+--------+--------------+--------------+
Balanced: true Usage:  0.00%
```

The etcdctl cluster-health is reported as healthy for all members.

**Comment by barakmich** [comment]
This almost looks like `torusblk` can't connect to the other peers (even if it claims to have with grpc? not sure). Is there a possibility that their network config is odd? But that hasn't changed...

**Comment by dghubble** [comment]
This seems to have been introduced by https://github.com/coreos/coreos-baremetal/commit/4d468484171c7ad8ff97900fb557d24eaa4b6fb6 which started using DNS names for peers instead of IPs.

**Comment by dghubble** [comment]
The failing writes don't seem related to this change. I've opened #333.

**Pull request merged**
