### PR TITLE
scripts: update rkt-gc-force for rkt 1.8.0

### PR DESCRIPTION
**Pull request by sym3tri**
the previous script was not working for me with rkt 1.8.0

### CODE REVIEW

**Comment by dghubble** [comment]
Did you see the update to https://github.com/coreos/coreos-baremetal/issues/208? In theory, the rkt-gc-force script would only be needed for rkt 1.6 and below, before the netns changes were made. I guess it depends if this still happened if rkt v.1.8 was the first version you've installed and it still happens?

I'm not sure what the netns naming was before, we'd probably want to keep the line that removed the pre-v1.6.0 netns's?

**Comment by sym3tri** [comment]
Need to consult with the rkt team for ideas.

FWIW 1.8.0 was the 1st and only version I ever installed on this machine.

**Comment by dghubble** [comment]
Hmm, that's not a promising sign that this is actually fixed.

**Comment by sym3tri** [comment]
No it's not.

Since each of those lines fail silently we could modify the script to do BOTH the old command and the new one. Admittedly a heavy-handed unattractive approach.

**Comment by dghubble** [comment]
Yeah, let's do that. If its a nuclear clean script, might as well clean for both versions.

**Comment by dghubble** [comment]
This doesn't seem to be enough

**Comment by dghubble** [comment]
Wrong button

**Comment by sym3tri** [comment]
@dghubble did that

**Pull request merged**
