### PR TITLE
Documentation: Show self-hosted Kubernetes upgrade process

### PR DESCRIPTION
**Pull request by dghubble**
I've upgraded several clusters to v1.4.3 and documented that process here.

cc @aaronlevy @sym3tri

### CODE REVIEW

**Comment by sym3tri** [comment]
Why is this in the bare-metal repo? Seems relevant to more than just bare-metal.

**Comment by aaronlevy** [comment]
Yeah, this would be great to have in bootkube repo too

**Comment by dghubble** [comment]
Yeah, it should work the same on cloud providers. I've performed the migration on QEMU/KVM clusters used in the self-hosted tutorial in this project and on real bare-metal clusters. This shouldn't matter for upgrades, but both those clusters still use https://github.com/kubernetes-incubator/bootkube/pull/151

**Comment by dghubble** [comment]
Do you want it, but without the bare-metal mentions? I can send a PR

**Comment by sym3tri** [comment]
maybe we put on coreos.com or tectonic.com?

**Comment by dghubble** [comment]
https://github.com/kubernetes-incubator/bootkube/pull/159

**Pull request merged**
