### PR TITLE
examples/ignition: Fix etcd peer listen urls to use IPs

### PR DESCRIPTION
**Pull request by dghubble**
* See github.com/coreos/etcd/pull/6365

cc @gyuho

### CODE REVIEW

**Comment by crawford** [comment]
Oof, binding on all interfaces isn't great. It's probably fine for the starter examples though. LGTM.

**Comment by dghubble** [comment]
These are reference clusters, if you have a better suggestion can you please share? I've explored approaches (for other reasons) which introspect for the current default interface's IP which could be used as the binding address here, but folks haven't been happy with introspection. Alternatives make assumptions about other services on the network.

**Comment by crawford** [comment]
> These are reference clusters

I think that is a fine stance to take. In order to get performance and security, the cluster needs to be tailored to its environment.

I think it's also reasonable to leverage coreos-metadata to determine exactly which interfaces should be bound, but that requires the user to modify the configs to match their environment.

**Comment by dghubble** [comment]
Rebased and added etcd3 and torus too.

**Pull request merged**
